### ISSUE TITLE
It don't work.

### ISSUE THREAD

**Issue by Tvde1** [aiham/reddit-oauth#2]
So I've copied your tutorial code, and filled it in with my credentials.

```
const RedditApi = require('reddit-oauth');
let reddit = new RedditApi({
	app_id: 'id',
	app_secret: 'secret',
	redirect_uri: 'http://google.com/'
});

reddit.passAuth(
	user, //user and pass are variables with my credentials
	pass,
	function (success) {
		if (success) {
			comment_stream.start();
		} else {
			console.log(':(');
		}
	}
);
```
And whenever I run this, the `:(` pops up.

**Comment by aiham** [comment]
@Tvde1 I just tested it and it worked. A couple of things you might want to double check since you're trying to use password access:

- Go to https://www.reddit.com/prefs/apps/
- Under **developed applications** make sure the app you created says **personal use script** and the username you're trying to authenticate with is added in the list of **developers**
- If you have the wrong type of app, you need to create a new app and select **script**:

![image](https://cloud.githubusercontent.com/assets/609164/23592850/060d2afe-025b-11e7-9bbe-024d9b27aabc.png)

Also make sure you've read https://www.reddit.com/wiki/api

If you want non developers to access your app then you cannot use `reddit.passAuth` but you must build a web application that redirects the user to the URL returned by `reddit.oAuthUrl` and retrieve the tokens with `reddit.oAuthTokens`. You can see https://github.com/aiham/RedditScrubber/tree/master/web as an example of how to use this library.

**Comment by Tvde1** [comment]
My apologies, I was using a script app from another account.
